# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "cmisid.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Projets CMI SID
  avatar: logoSID.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Bienvenue sur le site de présentation des projets de la formation CMI SID : Cursus Master Ingénierie en Statistique et Informatique Décisionnelle</p>

     
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://cmisid.univ-tlse3.fr/">CMI SID</a>

  # Icons
  rss: false
  email_address: contact.taxisid@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook: "taxisidtoulouse"
  flickr:
  github: "cmisid"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: TaxiSID
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Lire la suite"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
